networks:
  private_http_scheduler:
    external: false

services:
  database:
    image: postgres:17.4-alpine3.21
    ports:
      - 2432:5432
    networks:
      private_http_scheduler:
        aliases:
          - local_database
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=http_scheduler
  
  api:
    image: custom-go:latest
    ports:
      - 2480:8080
    networks:
      private_http_scheduler:
        aliases:
          - local_application
    volumes:
      - ${HOME}/personnal/HttpScheduler/:/app 
    tty: true
    command: /bin/sh /app/src/Api/_bootstrap/boot_api.sh
    env_file: ".env"
